name: Deploy workflow
on:
  pull_request:
    branches:
    - master

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: ./.github/actions/deploy
      env:
        KUBERNETES_DEPLOY_CA: ${{ secrets.KUBERNETES_DEPLOY_CA }}
        KUBERNETES_DEPLOY_SERVER: ${{ secrets.KUBERNETES_DEPLOY_SERVER }}
        KUBERNETES_DEPLOY_TOKEN: ${{ secrets.KUBERNETES_DEPLOY_TOKEN }}
        REVISION: ${{ github.sha }}
        SELF_REPO: https://github.com/${{ github.repository }}
        XENFORO2_REPO: ${{ secrets.XENFORO2_REPO }}
