name: Deploy workflow
on:
  pull_request:
    branches:
    - master

jobs:
  deploy_job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1
    - uses: ./.github/actions/deploy
